backend/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from . import views

app_name = "api"

schema_view = get_schema_view(
    openapi.Info(
        title="BigCorp API ",
        default_version="v1",
        description="BigCorp API description",
        terms_of_service="https://example.com/terms/",
        contact=openapi.Contact(email="admin@bigcorp.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
)

urlpatterns = [
    # Products
    path("products/", views.ProductListApiView.as_view()),
    path("products/<int:pk>/", views.ProductDetailAPIView.as_view()),
    # Reviews
    path('reviews/create/', views.ReviewCreateView.as_view()),
    # User
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    # Docs
    path('swagger/', schema_view.with_ui('swagger',
         cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc',
         cache_timeout=0), name='schema-redoc'),
]

backend/bigcorp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django_email_verification import urls as email_urls

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path("recommend/", include('recommend.urls', namespace='recommend')),
    path('email/', include(email_urls), name='email-verification'),
    path('api/v1/', include('api.urls', namespace='api')),
    path('', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/recommend/urls.py
from django.urls import path

app_name = 'recommend'

urlpatterns = [

]

backend/shop/urls.py
from django.urls import path

from .views import (ProductListView, category_list, products_detail_view,
                    search_products)

app_name = 'shop'

urlpatterns = [
    # path('', products_view, name='products'),
    path('', ProductListView.as_view(), name='products'),
    path("search_products/", search_products, name="search-products"),
    path('search/<slug:slug>/', category_list, name='category-list'),
    path('<slug:slug>/', products_detail_view, name='product-detail'),
]

backend/recommend/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from shop.models import Product

User = get_user_model()


class Review(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="reviews"
    )
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="reviews"
    )
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(1),
                                                          MaxValueValidator(5)])
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.created_by} on Product: {self.product}"

backend/recommend/views.py
from django.shortcuts import render

# Create your views here.

backend/recommend/templates/recommend/recommendation.html
<style>
    .reviews-container {
        width: 100%;
        margin-top: 6rem;
    }

    .reviews-title {
        font-size: 1.5rem;
    }

    .review-form {
        margin-top: 1rem;
        margin-bottom: 1rem;
        padding: 1rem;
        background-color: #f2f2f2;
        border-radius: 1rem;
    }

    .review-form label {
        font-weight: bold;
    }

    .review-form textarea {
        width: 100%;
        padding: 0.5rem;
        border: 1px solid #ccc;
        border-radius: 0.25rem;
    }

    review-form select {
        width: 50%;
        padding: 0.5rem;
        border: 1px solid #ccc;
        border-radius: 0.25rem;
    }

    .review-form button {
        margin-top: 1rem;
        padding: 0.5rem 1rem;
        background-color: #45EDAD;
        color: rgb(0, 0, 0);
        border: none;
        border-radius: 0.25rem;
        cursor: pointer;
    }

    .review {
        padding: 1rem;
        background-color: #f2f2f2;
        border-radius: 1rem;
        margin-bottom: 1rem;
    }

    .review strong {
        font-weight: bold;
    }

    .edit-pen {
        color: blue;
        cursor: pointer;
    }
</style>

<div class="reviews-container">
    <h2 class="reviews-title">Reviews</h2>

    {% if request.user.is_authenticated %}
    <form method="post" class="review-form">
        {% csrf_token %}
        <div>
            <label for="rating">Rating</label><br>
            <select name="rating" id="rating">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3" selected>3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>
        <div>
            <label for="content">Comment</label><br>
            <textarea name="content" id="content" rows="5" cols="50"></textarea>
        </div>
        <div>
            <button>Submit</button>
        </div>
    </form>
    {% endif %}

    {% for review in product.reviews.all %}
    <div class="d-flex flex-row bd-highlight mb-3 justify-content-between review " id="review-{{ review.id }}">
        <div>
            <strong>Date:</strong> {{ review.created_at|date:"Y-m-d" }}<br>
            <br>
            <strong>Rating:</strong> {{ review.rating }}/5<br>
            <strong>Comment:</strong><br>
            {{ review.content }}
        </div>
       {%  comment %}
        <div>
            {% if request.user.is_authenticated and request.user == review.created_by %}
            {% csrf_token %}
            <span class="edit-pen" hx-put="{% url 'shop:product-detail' product.slug %}">✏️</span>
            {% endif %}
        </div>
        {% endcomment %}
    </div>
    {% endfor %}
</div>